server:
  port: 9090
  servlet:
    context-path: /auth

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

spring:
  security:
    user:
      password: pass
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include: "*"

google:
  client:
    clientId: 96376170212-s1c4gi5s2ngkjblumrtc3mfbq1old5hp.apps.googleusercontent.com
    clientSecret: WPN-dU9WzRMnbiT9ubzWFu7m
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    tokenName: authorization_code
    scope: profile, email
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo






